# -*- coding: utf-8 -*-
"""Intellegent Manufacturing_Khirod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcWpsvXb_Fdb__tS0-gSv_XOA0wlvd8v
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('/content/manufacturing_6G_dataset.csv')
df.head()

# Separate features (X) and target (y)
X = df.drop('Efficiency_Status', axis=1)
y = df['Efficiency_Status']

# Encode the 'Operation_Mode' column
le = LabelEncoder()
X['Operation_Mode'] = le.fit_transform(X['Operation_Mode'])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train an SVM classifier
svm_classifier = SVC(kernel='linear') # You can experiment with different kernels
svm_classifier.fit(X_train, y_train)

# Make predictions
y_pred = svm_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))